"""
This module contains all the constants used in the game.
"""

GAME_TITLE = "Galactic Onslaught" # Game title
GAME_WIDTH = 1440 # Game window width
GAME_HEIGHT = 900 # Game window height
GAME_SPEED = 60 # Game speed (FPS)

# Define font properties
GAME_FONT_FAMILY = "Trebuchet MS"
GAME_FONT_SIZE = (18, 24, 32, 48)

# Define font color constants
GAME_FONT_COLOR = "white"
GAME_FONT_COLOR_ERROR = "#F36A68"
GAME_FONT_COLOR_WARNING = "#F9AE61"
GAME_FONT_COLOR_SUCCESS = "#84D792"

# Define font style constants
GAME_FONT_STYLE_NORMAL = "normal"
GAME_FONT_STYLE_BOLD = "bold"

# Define font constants
GAME_SMALLEST_FONT = (GAME_FONT_FAMILY, GAME_FONT_SIZE[0], GAME_FONT_STYLE_NORMAL)
GAME_SMALL_FONT = (GAME_FONT_FAMILY, GAME_FONT_SIZE[1], GAME_FONT_STYLE_NORMAL)
GAME_MEDIUM_FONT = (GAME_FONT_FAMILY, GAME_FONT_SIZE[2], GAME_FONT_STYLE_NORMAL)
GAME_LARGE_FONT = (GAME_FONT_FAMILY, GAME_FONT_SIZE[3], GAME_FONT_STYLE_NORMAL)

GAME_SMALL_FONT_BOLD = (GAME_FONT_FAMILY, GAME_FONT_SIZE[1], GAME_FONT_STYLE_BOLD)
GAME_MEDIUM_FONT_BOLD = (GAME_FONT_FAMILY, GAME_FONT_SIZE[2], GAME_FONT_STYLE_BOLD)
GAME_LARGE_FONT_BOLD = (GAME_FONT_FAMILY, GAME_FONT_SIZE[3], GAME_FONT_STYLE_BOLD)
