GAME_TITLE = "Space Invaders 3D" # Game title
GAME_WIDTH = 1440 # Game window width
GAME_HEIGHT = 900 # Game window height
GAME_SPEED = 60 # Game speed (FPS)

# Define font properties
GAME_FONT_FAMILY = "Consolas"
GAME_FONT_SIZE = (24, 32, 48)

# Define font color constants
GAME_FONT_COLOR = "white"
GAME_FONT_COLOR_ERROR = "red"
GAME_FONT_COLOR_WARNING = "orange"
GAME_FONT_COLOR_SUCCESS = "green"

# Define font style constants
GAME_FONT_STYLE_NORMAL = "normal"
GAME_FONT_STYLE_BOLD = "bold"

# Define font constants
GAME_SMALL_FONT = (GAME_FONT_FAMILY, GAME_FONT_SIZE[0], GAME_FONT_STYLE_NORMAL)
GAME_MEDIUM_FONT = (GAME_FONT_FAMILY, GAME_FONT_SIZE[1], GAME_FONT_STYLE_NORMAL)
GAME_LARGE_FONT = (GAME_FONT_FAMILY, GAME_FONT_SIZE[2], GAME_FONT_STYLE_NORMAL)

GAME_SMALL_FONT_BOLD = (GAME_FONT_FAMILY, GAME_FONT_SIZE[0], GAME_FONT_STYLE_BOLD)
GAME_MEDIUM_FONT_BOLD = (GAME_FONT_FAMILY, GAME_FONT_SIZE[1], GAME_FONT_STYLE_BOLD)
GAME_LARGE_FONT_BOLD = (GAME_FONT_FAMILY, GAME_FONT_SIZE[2], GAME_FONT_STYLE_BOLD)
